import React from 'react';
import Footer from '../components/Footer';

const Disclaimer = () => {
    return (
        <>
            <section className='w-full bg-[#EEF5FF] dark:bg-slate-900 duration-300 top-0 pt-10 pb-5 md:pb-10 md:pt-20'>
                <div className="max-w-2xl mx-auto p-6 bg-[#EEF5FF] dark:bg-slate-800 duration-300 dark:text-white text-black shadow-md rounded-md mt-5">
                    <h2 className="text-3xl font-semibold mb-6">Welcome to SkillEz</h2>

                    <p className="mb-4">
                        SkillEz is a platform designed to provide users with educational resources and skill-related content. Before you proceed, it's important to understand and acknowledge certain aspects of our service through the following disclaimer:
                    </p>

                    <h3 className="text-xl font-semibold mb-2">Purpose of Information:</h3>
                    <p className="mb-4">
                        The information provided on SkillEz is intended solely for educational and informational purposes. This includes details on skills, courses, and various resources, all of which are generated by contributors and users of the platform. It is crucial to recognize that this content may not always be completely accurate, up-to-date, or comprehensive.
                    </p>

                    <h3 className="text-xl font-semibold mb-2">No Guarantee of Accuracy:</h3>
                    <p className="mb-4">
                        SkillEz does not guarantee the accuracy or reliability of any information presented on this platform. Users are strongly advised to independently verify information, conduct thorough research, and seek guidance from qualified professionals before making any decisions based on the content available on SkillEz.
                    </p>

                    <h3 className="text-xl font-semibold mb-2">Use at Your Own Risk:</h3>
                    <p className="mb-4">
                        The use of SkillEz and its content is entirely at your own risk. SkillEz, along with its creators, contributors, and affiliates, will not be held liable for any damages, losses, or consequences that may arise from the use of the information provided on this platform.
                    </p>

                    <h3 className="text-xl font-semibold mb-2">Acknowledgment of Terms:</h3>
                    <p className="mb-4">
                        By accessing and using the SkillEz website, you acknowledge and agree to the terms outlined in this disclaimer. It is essential to take the time to read and understand these terms before proceeding with the use of our platform.
                    </p>

                    <h3 className="text-xl font-semibold mb-2">Content Review:</h3>
                    <p className="mb-4">
                        SkillEz values the contributions of its users and strives to provide accurate and reliable content. However, it is important to note that we cannot guarantee the authenticity of all submissions. If you come across any content that you believe to be inaccurate or inappropriate, we encourage you to report it to us for thorough review.
                    </p>

                    <p className="text-gray-600 dark:text-gray-300 text-sm mt-4">
                        In conclusion, SkillEz aims to foster a community of learners and contributors, but users are urged to exercise due diligence and caution when relying on the information available on our platform. If you have any questions or concerns regarding the content or accuracy of information on SkillEz, please do not hesitate to contact us.
                    </p>
                </div>
            </section>

            <Footer />
        </>
    );
}

export default Disclaimer;
